apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    task: 1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      task: 1-1
  template:
    metadata:
      labels:
        app: mongodb
        task: 1-1
    spec:
      hostNetwork: true
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        
