apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
--- # =======// Redis //========>>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    task: 1-1
spec:
  replicas: 1
  selector:
    matchLabels:
      task: 1-1
  template:
    metadata:
      labels:
        app: redis
        task: 1-1
    spec:
      hostNetwork: true
      containers:
      - name: redis
        image: bitnami/redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
--- # =======// Webapp -> Deployment //========>>
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectionmonitor
spec:
  selector:
    matchLabels:
      app: connectionmonitor
  template:
    metadata:
      labels:
        app: connectionmonitor
    spec:
      containers:
      - name: connectionmonitor
        image: apolloxiv/k8s:latest
        ports:
        - containerPort: 3000
--- # ========// Webapp -> Service //========>>
apiVersion: v1
kind: Service
metadata:
  name: connectionmonitor
spec:
  type: NodePort
  selector:
    app: connectionmonitor
  ports:
  - port: 3000
    targetPort: 3000
