apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    name: webserver
spec:
  containers:
  - name: webserver
    image: nginx:1.22-alpine
    ports:
      - containerPort: 80


# kubectl port-forward webserver 8080:80